# Generated by Django 4.1.7 on 2023-06-04 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_remove_post_image_post_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
